# Generated by Django 5.1.2 on 2026-05-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="huggingface_link",
            field=models.URLField(
                blank=True,
                help_text="Hugging Face Space or model URL (e.g. https://huggingface.co/spaces/username/app)",
            ),
        ),
    ]
